spring:
  application:
    name: springjdbc

  datasource:
    url: jdbc:mysql://localhost:3306/librarydb
    username: spring
    password: spring1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true