spring:
  application:
    name: restexam

  datasource:
    url: jdbc:mysql://localhost:3306/librarydb
    username: spring
    password: spring1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
